version: '3.7'

services:
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    #volumes:
    #  - "/home/miky/kafka/kafka-manager:/kafka-manager-1.3.1.8"
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: 172.19.0.2:2181,172.19.0.3:2181,172.19.0.4:2181                 ## 修改:宿主机IP
      TZ: CST-8
    networks:
      docker_net:
        ipv4_address: 172.19.0.8
networks:
  docker_net:
    external: true
