version: '3.7'

networks:
  docker_net:
    external: true

services:

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.5
      KAFKA_ADVERTISED_PORT: 9092                                 ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.5:9092    ## 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "172.19.0.2:2181,172.19.0.3:2181,172.19.0.4:2181"
    volumes:
      - "./kafka/kafka1/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka1/data/:/kafka"
    networks:
      docker_net:
        ipv4_address: 172.19.0.5


  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.6                 ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9092                               ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.6:9092   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "172.19.0.2:2181,172.19.0.3:2181,172.19.0.4:2181"
    volumes:
      - "./kafka/kafka2/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka2/data/:/kafka"
    networks:
      docker_net:
        ipv4_address: 172.19.0.6

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.7                 ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9092                              ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.7:9092   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "172.19.0.2:2181,172.19.0.3:2181,172.19.0.4:2181"
    volumes:
      - "./kafka/kafka3/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka3/data/:/kafka"
    networks:
      docker_net:
        ipv4_address: 172.19.0.7

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: 172.19.0.2:2181,172.19.0.3:2181,172.19.0.4:2181                 ## 修改:宿主机IP
      TZ: CST-8
    networks:
      docker_net:
        ipv4_address: 172.19.0.8
networks:
  docker_net:
    external: true
