version: '3.7'

networks:
  docker_net:
    external: true


services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.19.0.2:2888:3888 server.2=172.19.0.3:2888:3888 server.3=172.19.0.4:2888:3888
    volumes:
      - ./zookeeper/zoo1/data:/data
      - ./zookeeper/zoo1/datalog:/datalog
    networks:
      docker_net:
         ipv4_address: 172.19.0.2

  zoo2:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=172.19.0.2:2888:3888 server.2=172.19.0.3:2888:3888 server.3=172.19.0.4:2888:3888
    volumes:
      - ./zookeeper/zoo2/data:/data
      - ./zookeeper/zoo2/datalog:/datalog
    networks:
      docker_net:
         ipv4_address: 172.19.0.3

  zoo3:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=172.19.0.2:2888:3888 server.2=172.19.0.3:2888:3888 server.3=172.19.0.4:2888:3888
    volumes:
      - ./zookeeper/zoo3/data:/data
      - ./zookeeper/zoo3/datalog:/datalog
    networks:
      docker_net:
         ipv4_address: 172.19.0.4
